#############################################################################
# Makefile for building: so2sdr
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat May 12 16:22:05 2012
# Project:  so2sdr.pro
# Template: subdirs
# Command: /usr/bin/qmake -o Makefile so2sdr.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-qttelnet-buildlib \
		sub-qextserialport \
		sub-so2sdr

qttelnet/buildlib/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qttelnet/buildlib/ || $(MKDIR) qttelnet/buildlib/ 
	cd qttelnet/buildlib/ && $(QMAKE) /home/tclay/misc/radio/so2sdr.tmp/so2sdr.gcode/so2sdr-src-1.2.1/qttelnet/buildlib/buildlib.pro -o $(MAKEFILE)
sub-qttelnet-buildlib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qttelnet/buildlib/ || $(MKDIR) qttelnet/buildlib/ 
	cd qttelnet/buildlib/ && $(QMAKE) /home/tclay/misc/radio/so2sdr.tmp/so2sdr.gcode/so2sdr-src-1.2.1/qttelnet/buildlib/buildlib.pro -o $(MAKEFILE)
sub-qttelnet-buildlib: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE)
sub-qttelnet-buildlib-make_default-ordered: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) 
sub-qttelnet-buildlib-make_default: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) 
sub-qttelnet-buildlib-make_first-ordered: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) first
sub-qttelnet-buildlib-make_first: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) first
sub-qttelnet-buildlib-all-ordered: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) all
sub-qttelnet-buildlib-all: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) all
sub-qttelnet-buildlib-clean-ordered: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) clean
sub-qttelnet-buildlib-clean: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) clean
sub-qttelnet-buildlib-distclean-ordered: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qttelnet-buildlib-distclean: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qttelnet-buildlib-install_subtargets-ordered: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) install
sub-qttelnet-buildlib-install_subtargets: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) install
sub-qttelnet-buildlib-uninstall_subtargets-ordered: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-qttelnet-buildlib-uninstall_subtargets: qttelnet/buildlib/$(MAKEFILE) FORCE
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) uninstall
qextserialport/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qextserialport/ || $(MKDIR) qextserialport/ 
	cd qextserialport/ && $(QMAKE) /home/tclay/misc/radio/so2sdr.tmp/so2sdr.gcode/so2sdr-src-1.2.1/qextserialport/qextserialport.pro -o $(MAKEFILE)
sub-qextserialport-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qextserialport/ || $(MKDIR) qextserialport/ 
	cd qextserialport/ && $(QMAKE) /home/tclay/misc/radio/so2sdr.tmp/so2sdr.gcode/so2sdr-src-1.2.1/qextserialport/qextserialport.pro -o $(MAKEFILE)
sub-qextserialport: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE)
sub-qextserialport-make_default-ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-make_default-ordered  FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) 
sub-qextserialport-make_default: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) 
sub-qextserialport-make_first-ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-make_first-ordered  FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) first
sub-qextserialport-make_first: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) first
sub-qextserialport-all-ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-all-ordered  FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) all
sub-qextserialport-all: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) all
sub-qextserialport-clean-ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-clean-ordered  FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) clean
sub-qextserialport-clean: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) clean
sub-qextserialport-distclean-ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-distclean-ordered  FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qextserialport-distclean: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qextserialport-install_subtargets-ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-install_subtargets-ordered  FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) install
sub-qextserialport-install_subtargets: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) install
sub-qextserialport-uninstall_subtargets-ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-uninstall_subtargets-ordered  FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-qextserialport-uninstall_subtargets: qextserialport/$(MAKEFILE) FORCE
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) uninstall
so2sdr/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) so2sdr/ || $(MKDIR) so2sdr/ 
	cd so2sdr/ && $(QMAKE) /home/tclay/misc/radio/so2sdr.tmp/so2sdr.gcode/so2sdr-src-1.2.1/so2sdr/so2sdr.pro -o $(MAKEFILE)
sub-so2sdr-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) so2sdr/ || $(MKDIR) so2sdr/ 
	cd so2sdr/ && $(QMAKE) /home/tclay/misc/radio/so2sdr.tmp/so2sdr.gcode/so2sdr-src-1.2.1/so2sdr/so2sdr.pro -o $(MAKEFILE)
sub-so2sdr: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE)
sub-so2sdr-make_default-ordered: so2sdr/$(MAKEFILE) sub-qextserialport-make_default-ordered  FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) 
sub-so2sdr-make_default: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) 
sub-so2sdr-make_first-ordered: so2sdr/$(MAKEFILE) sub-qextserialport-make_first-ordered  FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) first
sub-so2sdr-make_first: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) first
sub-so2sdr-all-ordered: so2sdr/$(MAKEFILE) sub-qextserialport-all-ordered  FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) all
sub-so2sdr-all: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) all
sub-so2sdr-clean-ordered: so2sdr/$(MAKEFILE) sub-qextserialport-clean-ordered  FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) clean
sub-so2sdr-clean: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) clean
sub-so2sdr-distclean-ordered: so2sdr/$(MAKEFILE) sub-qextserialport-distclean-ordered  FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) distclean
sub-so2sdr-distclean: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) distclean
sub-so2sdr-install_subtargets-ordered: so2sdr/$(MAKEFILE) sub-qextserialport-install_subtargets-ordered  FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) install
sub-so2sdr-install_subtargets: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) install
sub-so2sdr-uninstall_subtargets-ordered: so2sdr/$(MAKEFILE) sub-qextserialport-uninstall_subtargets-ordered  FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-so2sdr-uninstall_subtargets: so2sdr/$(MAKEFILE) FORCE
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: so2sdr.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile so2sdr.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile so2sdr.pro

qmake_all: sub-qttelnet-buildlib-qmake_all sub-qextserialport-qmake_all sub-so2sdr-qmake_all FORCE

make_default: sub-qttelnet-buildlib-make_default-ordered sub-qextserialport-make_default-ordered sub-so2sdr-make_default-ordered FORCE
make_first: sub-qttelnet-buildlib-make_first-ordered sub-qextserialport-make_first-ordered sub-so2sdr-make_first-ordered FORCE
all: sub-qttelnet-buildlib-all-ordered sub-qextserialport-all-ordered sub-so2sdr-all-ordered FORCE
clean: sub-qttelnet-buildlib-clean-ordered sub-qextserialport-clean-ordered sub-so2sdr-clean-ordered FORCE
distclean: sub-qttelnet-buildlib-distclean-ordered sub-qextserialport-distclean-ordered sub-so2sdr-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-qttelnet-buildlib-install_subtargets-ordered sub-qextserialport-install_subtargets-ordered sub-so2sdr-install_subtargets-ordered FORCE
uninstall_subtargets: sub-qttelnet-buildlib-uninstall_subtargets-ordered sub-qextserialport-uninstall_subtargets-ordered sub-so2sdr-uninstall_subtargets-ordered FORCE

sub-qttelnet-buildlib-check_ordered: qttelnet/buildlib/$(MAKEFILE)
	cd qttelnet/buildlib/ && $(MAKE) -f $(MAKEFILE) check
sub-qextserialport-check_ordered: qextserialport/$(MAKEFILE) sub-qttelnet-buildlib-check_ordered 
	cd qextserialport/ && $(MAKE) -f $(MAKEFILE) check
sub-so2sdr-check_ordered: so2sdr/$(MAKEFILE) sub-qextserialport-check_ordered 
	cd so2sdr/ && $(MAKE) -f $(MAKEFILE) check
check: sub-qttelnet-buildlib-check_ordered sub-qextserialport-check_ordered sub-so2sdr-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

