######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 24 08:41:28 2010
######################################################################

TEMPLATE = app
include(../../src/qttelnet.pri)

TARGET = qtelnetperso
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindowimpl.h mytelnetwidget.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindowimpl.cpp mytelnetwidget.cpp
