#ifndef AFEDRICMD_H
#define AFEDRICMD_H

// from the source code of "sdr_commander"
// http://www.afedri-sdr.com

#define MSD_CLUSTER_SIZE 512
#define HID_COMMAND_MAX_SIZE 7
#define AFEDRI8201_MAIN_CLOCK 66.00e6
#define TRANSVERTER_MODE_LIMIT  1200000000
#define NCO_MULTIPLIER 4294967296.00
#define HID_MEMORY_READ_WRITE_REPORT 1
#define HID_FREQUENCY_REPORT 3
#define HID_GENERIC_REPORT 2
#define HID_GENERIC_GAIN_COMMAND 2
#define HID_GENERIC_INIT_FE_COMMAND 0xE1
#define HID_GENERIC_GET_FREQ_COMMAND 1
#define HID_GENERIC_GET_INIT_STATUS_COMMAND 4
#define HID_GENERIC_DAC_COMMAND 8
#define HID_GENERIC_VER_COMMAND 9
#define HID_GENERIC_CONSOLE_IO_COMMAND 10
#define HID_GENERIC_HID_CONSOLE_ON 11
#define HID_READ_EEPROM_COMMAND 0x55
#define HID_WRITE_EEPROM_COMMAND 0x56
#define HID_GENERIC_SAVE_DEFAULT_PARAMS_COMMAND 12
#define HID_GENERIC_GET_SR_COMMAND 14
#define HID_GENERIC_GET_DIVERSITY_MODE 15

#define HID_GENERIC_GET_SDR_IP_ADDRESS 16
#define HID_GENERIC_GET_SDR_IP_MASK 17
#define HID_GENERIC_GET_GATEWAY_IP_ADDRESS 18
#define HID_GENERIC_GET_DST_IP_ADDRESS 19
#define HID_GENERIC_GET_DST_PORT 20

#define HID_GENERIC_SAVE_SDR_IP_ADDRESS 21
#define HID_GENERIC_SAVE_SDR_IP_MASK 22
#define HID_GENERIC_SAVE_GATEWAY_IP_ADDRESS 23
#define HID_GENERIC_SAVE_DST_IP_ADDRESS 24
#define HID_GENERIC_SAVE_DST_PORT 25
#define HID_GENERIC_START_UDP_STREAM_COMMAND 26
#define HID_GENERIC_OVERLAOD_STATE 27
#define HID_GENERIC_ACK 28
#define HID_GENERIC_GET_SERIAL_NUMBER_COMMAND 29
#define HID_GENERIC_SET_SAMPLE_RATE_COMMAND 30
#define HID_GENERIC_SET_VCO_COMMAND 31
#define HID_GENERIC_GET_VCO_COMMAND 32
#define HID_GENERIC_SAVE_GAIN_TABLE_COMMAND 33
#define HID_GENERIC_GET_GAIN_TABLE_COMMAND 34
#define HID_GENERIC_SET_BPF_COMMAND 35
#define HID_GENERIC_SYNC_WORD_COMMAND 36
#define HID_GENERIC_HW_CPLD_SN_COMMAND 37
#define HID_GENERIC_IAP_COMMAND 38
#define HID_GENERIC_WRITE_HWORD_TO_FLASH 39
#define HID_GENERIC_BROADCAST_COMMAND 40
#define HID_GENERIC_GET_BROADCAST_STATE_COMMAND 41
#define HID_GENERIC_BYPASS_LPF_COMMAND 42
#define HID_GENERIC_GET_BYPASS_LPF_COMMAND 43
#define HID_GENERIC_SET_MULTICHANNEL_COMMAND 48
#define HID_GENERIC_MULTICAST_COMMAND 49
#define HID_GENERIC_SET_AFEDRI_ID_COMMAND 50
#define HID_GENERIC_GET_AFEDRI_ID_COMMAND 51
#define HID_GENERIC_SAVE_AFEDRI_ID_COMMAND 52
#define HID_GENERIC_SOFT_RESET_COMMAND 53
#define HID_GENERIC_GET_DHCP_STATE_COMMAND 54
#define HID_GENERIC_SET_DHCP_STATE_COMMAND 55
#define HID_GENERIC_SET_PHASE_SHIFT_COMMAND 56
#define HID_GENERIC_HW_CPLD2_SN_COMMAND 57
#define HID_GENERIC_I2C_SEND_COMMAND 58
#define HID_GENERIC_I2C_READ_COMMAND 59
#define HID_GENERIC_I2C_START_COND_COMMAND 60
#define HID_GENERIC_I2C_STOP_COND_COMMAND 61
#define HID_GENERIC_MULT_WRITE_JTAG_COMMAND 62
#define HID_GENERIC_GET_MAXIMUM_SR_COMMAND 63
#define HID_GENERIC_GET_MAIN_CLOCK_FREQ 67
#define HID_GENERIC_SET_USB_MODE        68
#define HID_GENERIC_SET_OVR_MODE        69
#define HID_GENERIC_AGC_LEVEL_COMMAND 70
#define HID_GENERIC_AGC_GET_STATE_COMMAND 71
#define HID_GENERIC_SET_MULTISTREAM_MODE    72
#define HID_GENERIC_GET_MULTISTREAM_MODE    73
#define HID_GENERIC_SAVE_MULTISTREAM_MODE    74
#define HID_SET_LED_ON_OFF                   75
#define HID_GENERIC_GET_DHCP_CLIENT_STATE_COMMAND 76
#define HID_GENERIC_SET_DHCP_CLIENT_STATE_COMMAND 77
#define HID_GENERIC_SET_R820T_FREQ_COMMAND 78
#define HID_GENERIC_SET_R820T_LNA_GAIN_COMMAND 79
#define HID_GENERIC_SET_R820T_MIXER_GAIN_COMMAND 80
#define HID_GENERIC_SET_R820T_VGA_GAIN_COMMAND 81
#define HID_GENERIC_SET_R820T_LNA_AGC_COMMAND 82
#define HID_GENERIC_SET_R820T_MIXER_AGC_COMMAND 83
#define HID_GENERIC_SET_R820T_IF_BW_COMMAND 84
#define HID_GENERIC_SET_R820T_PWR_ON_COMMAND 87
#define HID_GENERIC_SET_R820T_HIGHPASS_BW_COMMAND 88
#define HID_GENERIC_SET_R820T_LOWPASS_BW_COMMAND 89
#define HID_GENERIC_SAVE_R820T_REF_FREQ_COMMAND 90
#define HID_GENERIC_GET_R820T_REF_FREQ_COMMAND 91

#define TCP_HID_PACKET 0x7
#define HID_DEVICE_VID 0x483
#define HID_DEVICE_PID 0x5932

#define HID_DEVICE_ATEECS_VID 0x255D
#define HID_DEVICE_ATEECS_PID 0x0001
#define HID_DEVICE_SDR_NET_PID 0x0002
#define HID_DEVICE_ATEECS_PID_6 0x0006

#endif // AFEDRICMD_H
