#!/bin/bash
##
# This script is for recording a message. It takes one argument, the
# filename (without .wav). The message is recorded in mono.
#
# If already recording a message, the script stops the recording and exits
#
source ~/.so2sdr/wav/wav_settings

if (pgrep gst-launch-1.0 >& /dev/null)
then 
   pkill gst-launch-1.0
   exit
else
   pkill gst-launch-1.0
   pactl set-source-mute $mic 0
   gst-launch-1.0 -q pulsesrc ! 'audio/x-raw,rate=[32000,64000],format={S16LE,S24LE,S32LE},channels=1' ! wavenc ! filesink location=$1.wav &
fi
