#!/bin/bash
#
# stop playing audio (on either radio)
#
source ~/.so2sdr/wav/wav_settings
echo "\set_ptt 0" > /dev/tcp/$rigctld_ip0/$rigctld_port0
echo "\set_ptt 0" > /dev/tcp/$rigctld_ip1/$rigctld_port1

pkill gst-launch-1.0

#restore mic
pactl set-source-mute $mic 0
